In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df = pd.read_csv("downloads/StudentsPerformance.csv")

In [5]:
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

In [8]:
df.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [9]:
df.columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='object')

In [10]:
df.isnull().sum()

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

In [11]:
df.duplicated().sum()

np.int64(0)

In [12]:
df = df.drop_duplicates()

In [19]:
df.columns = df.columns.str.lower().str.replace(" ","_").str.replace("/","_")
df.head()

,gender,race-ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [20]:
df["total_score"] = df["math_score"] + df["reading_score"] + df["writing_score"]

In [23]:
df ["average_score"] = df["total_score"] / 3

In [25]:
df["result"] = np.where(
    (df["math_score"] >=35) &
    (df["reading_score"] >=35) &
    (df["writing_score"] >=35),
    "Pass",
    "Fail"
)

In [48]:
def grade_category(avg):
    if avg >= 90:
        return "Excellent"
    elif avg >= 75:
        return "Very Good"
    elif avg >= 60:
        return "good"
    elif avg >= 35:
        return "Average"
    else:
        return "Fail"
df["grade_category"] = df["average_score"].apply(grade_category)

In [49]:
df.head()

,gender,race-ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score,total_score,average_score,result,grade_category
0,female,group B,bachelor's degree,standard,none,72,72,74,218,72.666667,Pass,good
1,female,group C,some college,standard,completed,69,90,88,247,82.333333,Pass,Very Good
2,female,group B,master's degree,standard,none,90,95,93,278,92.666667,Pass,Excellent
3,male,group A,associate's degree,free/reduced,none,47,57,44,148,49.333333,Pass,Average
4,male,group C,some college,standard,none,76,78,75,229,76.333333,Pass,Very Good

In [50]:
avg_math = df["math_score"].mean()
avg_reading = df["reading_score"].mean()
avg_writing = df["writing_score"].mean()

print("Average Math Score:", avg_math)
print("Average Reading Score:", avg_reading)
print("Average Writing Score:", avg_writing)

Average Math Score: 66.089
Average Reading Score: 69.169
Average Writing Score: 68.054

In [51]:
print("Highest Math Score:", df["math_score"].max())
print("Lowest Math Score:", df["math_score"].min())

print("Highest Reading Score:", df["reading_score"].max())
print("Lowest Reading Score:", df["reading_score"].min())

print("Highest Writing Score:", df["writing_score"].max())
print("Lowest Writing Score:", df["writing_score"].min())

Highest Math Score: 100
Lowest Math Score: 0
Highest Reading Score: 100
Lowest Reading Score: 17
Highest Writing Score: 100
Lowest Writing Score: 10

In [52]:
df["result"].value_counts()

result
Pass    971
Fail     29
Name: count, dtype: int64

In [53]:
df["grade_category"].value_counts()

grade_category
good         391
Very Good    272
Average      267
Excellent     52
Fail          18
Name: count, dtype: int64

In [58]:
df.to_csv("cleaned_student_performane.csv", index=False)